language: node_js
node_js:
  - "12"
  - "14"
  - "16"

cache: yarn

env:
  - "NODE_ENV=test"

branches:
  only:
    - develop
    - master

install:
  - yarn

before_script:
  - yarn test:coverage
  - yarn
  - yarn start&

script:
  - sleep 10
  # Requires Apollo Graph Manger Team Plan ;_;
  # - yarn schema:check -- --tag=$TRAVIS_BRANCH
  - yarn schema:push --variant=$TRAVIS_BRANCH
