language: node_js
node_js:
  - "12"

cache: yarn

env:
  - NODE_ENV: test

branches:
  only:
  - develop
  - master

install:
  - yarn

before_script:
  - yarn test:coverage
  - yarn
  - yarn start&

# Requires Apollo Graph Manger Team Plan ;_;
# script:
  # - sleep 10
  # - apollo service:check --tag=$TRAVIS_BRANCH

deploy:
  # deploy develop to the staging environment
  - provider: script
    skip_cleanup: true
    script: yarn deploy:dev
    on:
      node: "12"
      branch: develop
  # deploy master to production
  - provider: script
    skip_cleanup: true
    script:
      - yarn deploy:prod
      - apollo service:publish
    on:
      node: "12"
      branch: master
