service: "mini-movie-db-api"

provider:
  name: aws
  runtime: "nodejs12.x"
  region: "us-west-2"
  stage: ${opt:stage, "dev"}
  environment:
    stage: ${self:provider.stage}
    MOVIE_DB_API_KEY: ${env:MOVIE_DB_API_KEY}
    ENGINE_API_KEY: ${env:ENGINE_API_KEY}

plugins:
  - "serverless-dotenv-plugin"
  - "serverless-webpack"
  - "serverless-offline"

package:
  exclude:
    - "./ node_modules/**"
    - "./.eslintrc.json"
    - "./webpack.config.js"

custom:
  serverless-offline:
    httpPort: 1337
  webpack:
    includeModules: true
    webpackConfig: "webpack.config.js"

functions:
  graphql:
    handler: "src/index.graphqlHandler"
    events:
      - http:
          path: "{proxy+}"
          method: any
          cors: true
